// GM console (only for the GM): invites, live rule tuning, player tools, cross-player reports, audit log.
import { defineClientPlugin } from '../../core/game';
import GmBadge from './GmBadge.vue';
import GmPanel from './GmPanel.vue';

export default defineClientPlugin({
	id: 'gm-panel',
	dependsOn: ['auth'],
	setup(game) {
		if (!game.use('auth').user.gm) return;
		game.messages('zh-CN', {
			GM: 'GM',
			'GM console': 'GM 控制台',
			Players: '玩家',
			Rules: '规则',
			Reports: '报表',
			Invites: '邀请码',
			Audit: '审计',
			Broadcast: '群发',
			'Mail to every player': '给所有玩家发邮件',
			Title: '标题',
			Message: '正文',
			'Send to everyone': '发送给所有人',
			'Send this mail to every player?': '把这封邮件发给所有玩家？',
			'Sent to {n} players': '已发送给 {n} 名玩家',
			Announcement: '公告',
			'Shown at the top of every page until each player dismisses it. Empty: none.':
				'显示在每个页面顶部，直到玩家点"知道了"；留空则不显示。',
			Player: '玩家',
			Capital: '首都',
			'Nothing yet.': '暂无记录。',
			// audit log actions (an unknown one shows as it is)
			'audit:player.command': '对玩家执行命令',
			'audit:player.play': '以玩家身份游玩',
			'audit:config.set': '修改规则',
			'audit:config.reset': '恢复规则默认值',
			'audit:config.prune': '清除失效的规则覆盖',
			'audit:mail.broadcast': '群发邮件',
			'Max uses': '可用次数',
			'Expires (hours)': '有效期（小时）',
			never: '永久',
			Note: '备注',
			'Create invite': '生成邀请码',
			'No invites yet.': '还没有邀请码。',
			Code: '邀请码',
			Uses: '已用',
			Expires: '过期时间',
			revoked: '已作废',
			'Copy link': '复制链接',
			Revoke: '作废',
			When: '时间',
			Who: '操作者',
			Action: '操作',
			Detail: '详情',
			'Play as this player': '以其身份游玩',
			'Play as {name}? You leave the GM account: to come back, log out and log in as the GM.':
				'以 {name} 的身份游玩？将退出 GM 账户；要回到 GM 界面，需要退出登录后用 GM 账号重新登录。',
			'plugin:engine': '引擎',
			'plugin:kernel': '引擎',
			'plugin:gm': 'GM',
			// rules
			Saved: '已保存',
			changed: '已修改',
			'Stored override ignored': '已存的覆盖值无效，已忽略',
			Save: '保存',
			Undo: '撤销',
			'Reset to default': '恢复默认',
			Remove: '删除',
			'add…': '添加…',
			'(empty)': '（空）',
			row: '行',
			levels: '等级表',
			cost: '费用',
			seconds: '秒数',
			costGrowth: '费用递增',
			timeGrowth: '时间递增',
			cap: '上限',
			produces: '产出',
			baseCost: '基础费用',
			defense: '防御',
			units: '兵种',
			'Changes apply to every player immediately, including their pending offline time.':
				'修改会立即对所有玩家生效，包括尚未结算的离线时间。',
			// reports
			Report: '报表',
			Parameters: '参数',
			Run: '运行',
			'No rows.': '没有数据。',
			playerId: '玩家ID',
			username: '玩家',
			holder: '持有者',
			amount: '数量',
			perSecond: '每秒',
			resource: '资源',
			pools: '资源池数',
			total: '总量',
			average: '平均',
			totalPerSecond: '每秒总产',
			kind: '类型',
			name: '名称',
			id: 'ID',
			x: 'x',
			y: 'y',
			extraDistricts: '外城数',
			building: '建筑',
			settlement: '城池',
			district: '城区',
			slot: '栏位',
			level: '等级',
			min: '最小值',
			limit: '条数上限',
			owner: '拥有者',
			// the value editor
			'(grows from the level below)': '（按下一级推算）',
			'Fill in': '填写',
			'Choose one to edit…': '选择要修改的一项…',
			'empty row': '空行',
		});
		// Opened from the GM badge next to the user name (both placed by the server; only the GM's client has them).
		game.widget('gm.panel', GmPanel);
		game.widget('gm.badge', GmBadge);
	},
});
