// GM console (only for the GM): invites, live rule tuning, player tools, cross-player reports, audit log.
import { defineClientPlugin } from '../../core/game';
import GmPanel from './GmPanel.vue';

export default defineClientPlugin({
	id: 'gm-panel',
	dependsOn: ['auth'],
	setup(game) {
		if (!game.use('auth').user.gm) return;
		game.messages('zh-CN', {
			GM: 'GM',
			'GM console': 'GM 控制台',
			Players: '玩家',
			Rules: '规则',
			Reports: '报表',
			Invites: '邀请码',
			Audit: '审计',
			Player: '玩家',
			'plugin:resources': '资源',
			'plugin:buildings': '建筑',
			'plugin:settlements': '城池',
			'plugin:research': '科技',
			'plugin:items': '道具',
			'plugin:troops': '部队',
			'plugin:npc-camps': 'NPC',
			'plugin:timeline': '时间线',
			'plugin:engine': '引擎',
			'plugin:kernel': '引擎',
			'plugin:player-settlements': '城池类型',
			'plugin:starter-content': '内容',
			'plugin:armies': '行军',
			'plugin:gm': 'GM',
			// rules
			Saved: '已保存',
			changed: '已修改',
			'Stored override ignored': '已存的覆盖值无效，已忽略',
			Save: '保存',
			Undo: '撤销',
			'Reset to default': '恢复默认',
			Remove: '删除',
			'add…': '添加…',
			'(empty)': '（空）',
			row: '行',
			levels: '等级表',
			cost: '费用',
			seconds: '秒数',
			costGrowth: '费用递增',
			timeGrowth: '时间递增',
			cap: '上限',
			produces: '产出',
			baseCost: '基础费用',
			defense: '防御',
			units: '兵种',
			'Changes apply to every player immediately, including their pending offline time.':
				'修改会立即对所有玩家生效，包括尚未结算的离线时间。',
			'Offline progress cap in seconds. Time beyond this is lost.': '离线收益上限（秒），超出部分作废。',
			'Global research speed multiplier (2 = twice as fast).': '全局研究速度倍率（2 = 两倍速）。',
			'Build speed multiplier (2 = everything builds twice as fast).': '建造速度倍率（2 = 两倍速）。',
			'Training speed multiplier (2 = twice as fast).': '训练速度倍率（2 = 两倍速）。',
			'Marching speed multiplier (2 = armies travel twice as fast).': '行军速度倍率（2 = 两倍速）。',
			'Global multiplier on all building output (events, balancing).': '所有建筑产出的全局倍率（活动、平衡用）。',
			'Storage cap per resource before bonuses (warehouses etc. add to it).': '每种资源的基础库存上限（仓库等会在此基础上增加）。',
			'Simultaneous constructions per settlement before bonuses.': '每座城的基础同时建造数。',
			'Share of the cost returned when a construction is cancelled (0-1).': '取消建造时返还的费用比例（0–1）。',
			'How many NPC camps of each kind the world keeps; a background task tops up missing ones (at most 5 per minute). 0 = off.':
				'世界保持的各类 NPC 营地数量，后台任务每分钟最多补充 5 个。0 = 关闭。',
			// reports
			Report: '报表',
			Parameters: '参数',
			Run: '运行',
			'No rows.': '没有数据。',
			playerId: '玩家ID',
			username: '玩家',
			holder: '持有者',
			amount: '数量',
			perSecond: '每秒',
			resource: '资源',
			pools: '资源池数',
			total: '总量',
			average: '平均',
			totalPerSecond: '每秒总产',
			kind: '类型',
			name: '名称',
			id: 'ID',
			x: 'x',
			y: 'y',
			extraDistricts: '外城数',
			building: '建筑',
			settlement: '城池',
			district: '城区',
			slot: '栏位',
			level: '等级',
			min: '最小值',
			limit: '条数上限',
			owner: '拥有者',
			'Pools with the most of a resource (estimated now), optionally at least `min`.': '某种资源最多的资源池（估算当前值），可设最小值。',
			'Economy overview: per resource, number of pools, total and average (estimated now).':
				'经济概况：每种资源的资源池数、总量和平均值（估算当前值）。',
			'Settlements, optionally filtered by `kind` and/or `owner` (player id).': '城池列表，可按类型和拥有者（玩家ID）筛选。',
			'Highest instances of a building type across all settlements.': '全服某种建筑的最高等级实例。',
			// GM forms
			'Grant resources': '发放资源',
			Settlement: '城池',
			Resource: '资源',
			'Amount (negative to take)': '数量（负数为扣除）',
			Grant: '发放',
			'Raise a building level cap': '提高建筑等级上限',
			Levels: '级数',
			'Raise cap': '提高上限',
			'Add an outer city beyond the research limit': '越过科技上限建外城',
			'Add outer city': '建外城',
			'Set a tech level': '设置科技等级',
			Tech: '科技',
			Level: '等级',
			'Set level': '设置',
			'Register a new tech node': '注册新科技节点',
			'A tech outside the tree (what an opaque-tree discovery creates). One cost row: later levels grow from it.':
				'科技树之外的科技（不透明科技的发现）。只填一级费用，之后逐级递增。',
			'Id (a-z, 0-9, -)': 'ID（a-z、0-9、-）',
			'Max level': '最高等级',
			'Gold per level': '每级金币',
			'Seconds per level': '每级秒数',
			'Bonus to': '加成项',
			'Bonus % per level': '每级加成 %',
			'Visible to everyone (otherwise only this player)': '所有人可见（否则仅该玩家）',
			Register: '注册',
			'Give items': '发放道具',
			Item: '道具',
			'Count (negative to take)': '数量（负数为扣除）',
			Give: '发放',
			'Add or remove troops': '增减部队',
			'Count (negative to remove)': '数量（负数为减少）',
			Apply: '执行',
			'Spawn NPC camps at random': '随机生成 NPC 营地',
			Kind: '类型',
			Count: '数量',
			Spawn: '生成',
			'Place an NPC camp': '放置 NPC 营地',
			Place: '放置',
		});
		game.page('gm', 'GM', GmPanel, { order: 100 });
	},
});
