// Chinese descriptions of the rules that belong to no server plugin (the kernel's). Every plugin's own rule
// descriptions ship with it ("rule:<key>" in its data/i18n.csv). A rule missing everywhere shows its English description.
export const rulesZh: Record<string, string> = {
	'engine.maxOfflineSeconds': '离线结算的上限（秒）。超过这段时间的离线产出作废。',
};

// Field names inside rule values (the editor shows content ids by their names, everything else from here).
export const fieldsZh: Record<string, string> = {
	levels: '各级',
	cost: '费用',
	seconds: '时长（秒）',
	costGrowth: '费用递增',
	timeGrowth: '时长递增',
	cap: '等级上限',
	crushing: '碾压',
	victory: '胜利',
	narrow: '险胜',
	'narrow-defeat': '惜败',
	routed: '溃败',
	expBase: '经验基数',
	expPower: '经验指数',
	maxLevel: '最高等级',
	freePerLevel: '每级自由点',
	groupSeconds: '每组耗时（秒）',
	minDamage: '最低伤害比例',
	sitesPerRealm: '每个秘境的入口数',
	heal: '治疗',
	secondsPerLevel: '每级秒数',
	dropTiers: '掉率档位',
	common: '常见',
	uncommon: '少见',
	base: '基数',
	specialty: '特长加成',
	tier2: '2 级',
	tier2Specialty: '2 级特长加成',
	growth: '每级倍率',
	specialtyGrowth: '特长每级倍率',
	cavalry1: '1 级骑兵倍率',
	cavalryGrowth: '骑兵每级倍率',
	costExponent: '费用指数',
	timeExponent: '时长指数',
	perHour: '每小时',
	exponent: '指数',
	step: '每级步长',
	linearUntil: '线性到第几级',
	factor: '之后每级倍率',
	tier1: '1 级',
	tier3: '3 级',
	tier4: '4 级',
	medic: '军医',
	save: '每人救回',
	bonusEvery: '每几级加成一次',
	bonusStep: '每次加成',
	bonusMax: '加成上限',
	levelsPerSlot: '每几级多一个候选',
	hours: '小时',
	hoursPerLevel: '每级小时',
	minHours: '最少小时',
	governors: '内政',
	scholars: '研究',
	commanders: '带兵',
	defenders: '守城',
	perPoint: '每点',
	battlePerPoint: '战斗每点 %',
	battleLevelPower: '战斗等级指数',
	flatLevelPower: '固定值等级指数',
	duty: '职务',
	attribute: '属性',
	stat: '数值',
	kind: '类型',
	target: '目标',
	value: '数值',
	atLevel: '第几级时',
	family: '兵种系列',
	days: '天数',
	rate: '衰减',
	normal: '常规值',
	pity: '保底',
	attack: '攻击',
	defense: '防御',
	hp: '生命',
	groupStep: '组间递增',
	boss: '首领倍率',
	perRealm: '每阶秘境',
	perResource: '每资源声望',
	normalMinutes: '普通间隔（分钟）',
	minMinutes: '最短（分钟）',
	maxMinutes: '最长（分钟）',
	jitter: '随机幅度',
	protection: '新手保护',
	prestige: '声望',
	lossFactor: '失败折算',
	winFactor: '胜利折算',
	ranksPerLevel: '每级流寇的官职数',
	spread: '随机浮动',
	first: '第一件',
	second: '第二件',
	lead: '到达时间（分钟）',
	interval: '出现间隔',
	level: '等级',
	capitalWeight: '首都权重',
	freshHours: '新城免挑（小时）',
	resourceDrop: '资源掉落',
	perLevel: '每级',
	recentHours: '近期时长（小时）',
	recovery: '恢复',
	luck: '幸运',
	drop: '掉落',
	weight: '权重',
	accessory: '饰品',
	variance: '浮动',
	smelt: '拆解',
	total: '总量',
	shop: '商店',
	price: '价格',
	reference: '基准值',
	upkeep: '维持',
	shares: '分摊比例',
	upkeepShares: '维持分摊',
	maxBatch: '单次上限',
	name: '名称',
	stockade: '寨栅',
	lane: '每路兵数',
	loot: '可抢',
	bias: '资源偏置',
	heroes: '守将人数',
	heroAttack: '守将攻击 %',
	heroDefense: '守将防御 %',
	heroHp: '守将生命 %',
	heroCasualty: '守将伤亡 %',
};
